### ISSUE TITLE
qts1kpcie_status_plugin which does not exist

### ISSUE THREAD

**Issue by muweigg** [ILOVEPIE/qts1kpcie_wifi_driver#4]
Hi

Openwrt: v18.06.2
Netgear: r7500v1
Ubuntu: 18.04

Put both kernel and net folders in the package, and then run make defconfig tip:

WARNING: Makefile 'package/net/qts1kpcierpc/Makefile' has a dependency on 'qts1kpcie_status_plugin', which does not exist

How to successfully compile and use 5GHz, can you guide me?

**Comment by ILOVEPIE** [comment]
The driver requires some work before it can be used, specifically hardware NAT support needs to be added back into the driver. I don't have the time currently but I am open to PRs if you want to try tackling it.
